<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Automation - Register - Apply for License - Issue License</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>eba7cf43-ed78-4031-b611-be67bd5ea59e</testSuiteGuid>
   <testCaseLink>
      <guid>7db7c4a7-b2d6-4bf9-a138-403e63bb9c61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Successful - US Citizen - With SSN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a911b9e4-f27f-4e3a-8f3b-4b8a44ea2ce1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c16edb5a-08ec-4c32-8cf4-5b8fb57dbb70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1a3ae38-d74e-4712-bce0-24a7dcaaf4fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70617006-c77c-4821-8fdb-936830a9b03c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>917bf4a7-68a0-4579-8c94-2b733d3eda20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Reset Password and Complete Registration Process</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>830c0b7e-e85f-43c5-b787-d1a8b0899358</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit License Application/Apply for a License - Physical Therapist</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01db107b-17ea-4fe4-ac1f-4291ffa8aa1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b97fd85f-21d5-448b-98fd-f4b45f450720</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6037fc2-b2cf-4608-b4f6-81835fe70f58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a200090-67b3-438e-90ca-29de4ef8a608</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ed8ce27-d803-4f20-89bb-2d1e6d81dc5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit License Application/Approve Physical Therapist Checklist Tasks</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>aa5be3be-2f9c-4ea7-851a-04d49fc9ec46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit License Application/Approve License Application</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0d700b15-9554-4479-9ce0-70f7381d47a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit License Application/Issue License</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
