<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Here are listed the test cases where the User who is trying to register is already registered.</description>
   <name>Duplicated Registrations</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b82cdab4-bc4f-4199-8a8a-b0e96225bf57</testSuiteGuid>
   <testCaseLink>
      <guid>779c3cf0-4b07-4c3c-a0f3-7f09d02c5d29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - US Citizen - Email-SSN Duplicated</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7921acd-df9e-4a9a-bd73-d1a021bf83ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>528b66d6-b585-4a98-bd2e-1f70465e86a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>025b7e82-593a-4d53-8a19-e8f38ae9a0c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446dec11-c803-41b4-9b8f-56e9674e3fcb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5329ef2-1346-418f-ad84-abff028cb8f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - No Citizen - Email-I94 Duplicated</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15110820-85fa-4da5-9b59-2cf3d9c70ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d208e6d-4188-400c-9db3-9ea60cd614f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>201b00ef-86de-4428-b484-d870f61008b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d39c27-68a8-414f-a8f5-107c737ffbfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d9098ce-923e-4145-84e2-4b66730af5f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Licensure Unit User Registration/Registration Failed - No Citizen - Email-AlienRegistrationNum Duplicated</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9f2be25-c204-44de-992b-799cd6006f84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>085cb172-7860-431b-bb0e-30122faf768a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f85fa27-c614-4a4e-a466-2c560de4abeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a661c61-8886-465f-bc93-b69bc8f90c3d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
